name: Resource provision
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: terraform provider
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: terraform token
        uses: aws-actions/configure-aws-credentials@v5
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            role-to-assume: arn:aws:iam::353075014684:role/Genpact-POC-PowerUser 
            aws-region: us-east-1
      - name: terraform init
        run: terraform init -input=false
      - name: terraform plan
        run: terraform plan -input=false
      - name: terraform apply
        run: terraform apply -auto-approve -input=false
